workspace = { }
[package]
name = "cpu_ray_tracing"
version = "0.5.0"
edition = "2021"

[dependencies]
rand = "0.6.0"
rayon = "1.8.0"
sdl2 = "0.35"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
